server:
  tomcat:
    max-swallow-size: 1024MB
    max-http-form-post-size: 1024MB
spring:
  application:
    name: course-service
  config:
    import: "optional:configserver:${SPRING_CONFIG_IMPORT_URL:http://localhost:8888}"
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  profiles:
    active: dev
