server:
  tomcat:
    max-swallow-size: 500MB
    max-http-form-post-size: 500MB
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:postgresql://postgres:5432/coursedb
    username: smartuser
    password: smartpass

app:
  upload:
    dir: /app/uploads
    url-prefix: http://127.0.0.1:8080/api/courses/uploads/
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.web: DEBUG
    com.smartlearn.course: DEBUG
